// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PublicDataDbContext))]
    partial class PublicDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");

            modelBuilder.Entity("Data.AnoEleicaoRecord", b =>
                {
                    b.Property<int>("Ano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ano"));

                    b.HasKey("Ano");

                    b.ToTable("anos_eleicao", "tse");
                });

            modelBuilder.Entity("Data.BemDeclaradoRecord", b =>
                {
                    b.Property<string>("CandidatoCpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<string>("TipoBem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CandidatoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidatoNomeUrna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CandidatoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartidoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("PartidoSigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CandidatoCpf", "AnoEleicao", "TipoBem", "Descricao");

                    b.ToTable("bens_declarados", "tse");
                });

            modelBuilder.Entity("Data.CandidatoRecord", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeUrna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("PartidoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("PartidoSigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Cpf", "AnoEleicao");

                    b.ToTable("candidatos", "tse");
                });

            modelBuilder.Entity("Data.ColigacaoRecord", b =>
                {
                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<string>("PartidosJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Nome", "AnoEleicao");

                    b.ToTable("coligacoes", "tse");
                });

            modelBuilder.Entity("Data.DadoDesempregoRecord", b =>
                {
                    b.Property<string>("UfSigla")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("TrimestreAno")
                        .HasColumnType("integer");

                    b.Property<int>("TrimestreNumero")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxaDesemprego")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("UfSigla", "TrimestreAno", "TrimestreNumero");

                    b.HasIndex("TrimestreAno", "TrimestreNumero");

                    b.ToTable("dados_desemprego", "pnad");
                });

            modelBuilder.Entity("Data.DadoEscolaridadeRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("NivelEscolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "NivelEscolaridade");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_escolaridade", "ibge");
                });

            modelBuilder.Entity("Data.DadoInformalidadeRecord", b =>
                {
                    b.Property<string>("UfSigla")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("TrimestreAno")
                        .HasColumnType("integer");

                    b.Property<int>("TrimestreNumero")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxaInformalidade")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("UfSigla", "TrimestreAno", "TrimestreNumero");

                    b.HasIndex("TrimestreAno", "TrimestreNumero");

                    b.ToTable("dados_informalidade", "pnad");
                });

            modelBuilder.Entity("Data.DadoInfraestruturaRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("TipoInfraestrutura")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DomiciliosAtendidos")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "TipoInfraestrutura");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_infraestrutura", "ibge");
                });

            modelBuilder.Entity("Data.DadoPopulacionalRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("FaixaEtaria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Raca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "FaixaEtaria", "Raca");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_populacionais", "ibge");
                });

            modelBuilder.Entity("Data.DadoRendaMediaRecord", b =>
                {
                    b.Property<string>("UfSigla")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("TrimestreAno")
                        .HasColumnType("integer");

                    b.Property<int>("TrimestreNumero")
                        .HasColumnType("integer");

                    b.Property<decimal>("RendaMedia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("UfSigla", "TrimestreAno", "TrimestreNumero");

                    b.HasIndex("TrimestreAno", "TrimestreNumero");

                    b.ToTable("dados_renda_media", "pnad");
                });

            modelBuilder.Entity("Data.DadoRendaRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("FaixaRenda")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "FaixaRenda");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_renda", "ibge");
                });

            modelBuilder.Entity("Data.DadoSaneamentoRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("TipoSaneamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DomiciliosAtendidos")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "TipoSaneamento");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_saneamento", "ibge");
                });

            modelBuilder.Entity("Data.SetorCensitarioRecord", b =>
                {
                    b.Property<string>("CodigoSetor")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<MultiPolygon>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4674)");

                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("CodigoSetor");

                    b.HasIndex("Geometria")
                        .HasMethod("gist");

                    b.HasIndex("MunicipioCodigoIbge");

                    b.HasIndex("UfSigla");

                    b.ToTable("setores_censitarios", "ibge");
                });

            modelBuilder.Entity("Data.DadoUrbanizacaoRecord", b =>
                {
                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("TipoArea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Populacao")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("MunicipioCodigoIbge", "TipoArea");

                    b.HasIndex("UfSigla");

                    b.ToTable("dados_urbanizacao", "ibge");
                });

            modelBuilder.Entity("Data.MunicipioRecord", b =>
                {
                    b.Property<int>("CodigoIbge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoIbge"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("CodigoIbge");

                    b.HasIndex("UfSigla", "Nome");

                    b.ToTable("municipios", "tse");
                });

            modelBuilder.Entity("Data.PartidoRecord", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Numero"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Numero");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("partidos", "tse");
                });

            modelBuilder.Entity("Data.PerfilEleitoradoRecord", b =>
                {
                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroZona")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("FaixaEtaria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuantidadeEleitores")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("AnoEleicao", "NumeroZona", "MunicipioCodigoIbge", "FaixaEtaria", "Escolaridade", "Genero");

                    b.HasIndex("MunicipioCodigoIbge", "AnoEleicao");

                    b.ToTable("perfis_eleitorado", "tse");
                });

            modelBuilder.Entity("Data.PrestacaoContasRecord", b =>
                {
                    b.Property<string>("CandidatoCpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<string>("TipoReceita")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoMovimentacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CandidatoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidatoNomeUrna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CandidatoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartidoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("PartidoSigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CandidatoCpf", "AnoEleicao", "TipoReceita", "Descricao", "TipoMovimentacao");

                    b.ToTable("prestacoes_contas", "tse");
                });

            modelBuilder.Entity("Data.ResultadoEleitoralRecord", b =>
                {
                    b.Property<string>("CandidatoCpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("AnoEleicao")
                        .HasColumnType("integer");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroZona")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroSecao")
                        .HasColumnType("integer");

                    b.Property<string>("CandidatoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidatoNomeUrna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CandidatoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PartidoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidoNumero")
                        .HasColumnType("integer");

                    b.Property<string>("PartidoSigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("QuantidadeVotos")
                        .HasColumnType("integer");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("CandidatoCpf", "AnoEleicao", "Turno", "NumeroZona", "MunicipioCodigoIbge", "NumeroSecao");

                    b.HasIndex("MunicipioCodigoIbge", "AnoEleicao");

                    b.HasIndex("PartidoNumero", "AnoEleicao");

                    b.HasIndex("NumeroZona", "MunicipioCodigoIbge", "AnoEleicao");

                    b.ToTable("resultados_eleitorais", "tse");
                });

            modelBuilder.Entity("Data.SecaoEleitoralRecord", b =>
                {
                    b.Property<int>("NumeroSecao")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroZona")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("NumeroSecao", "NumeroZona", "MunicipioCodigoIbge");

                    b.ToTable("secoes_eleitorais", "tse");
                });

            modelBuilder.Entity("Data.TrimestreRecord", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Ano", "Numero");

                    b.ToTable("trimestres", "pnad");
                });

            modelBuilder.Entity("Data.UfRecord", b =>
                {
                    b.Property<string>("Sigla")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Sigla");

                    b.ToTable("ufs", "tse");
                });

            modelBuilder.Entity("Data.ZonaEleitoralRecord", b =>
                {
                    b.Property<int>("NumeroZona")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioCodigoIbge")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UfSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("NumeroZona", "MunicipioCodigoIbge");

                    b.ToTable("zonas_eleitorais", "tse");
                });
#pragma warning restore 612, 618
        }
    }
}
